version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  image: devopsevd/jenkins:2.60.1
  ports:
    - "8080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
